### PR TITLE
Add tree widget

### PR DESCRIPTION
**Pull request by mcon**
As per the issue (https://github.com/spectresystems/spectre.console/issues/144) I've added the ability to render a tree of `IRenderable`s - let me know what you think.

## TODO:
 - [x] Doc comments on all public methods

### CODE REVIEW

**Comment by patriksvensson** [comment]
@mcon Oooh, looks awewome. Not in a position to review it right now, but I'll get on it first thing when I have some "me time". Great work! 👍

**Comment by patriksvensson** [comment]
@mcon Is this ready for review?

**Comment by mcon** [comment]
I'd say so, yes

**Review by patriksvensson — APPROVED** [review]
LGTM!

**Pull request merged**
