### PR TITLE
Allow setting progress value directly

### LINKED ISSUE #272: Allow setting progress value directly
Currently the ProgressTask only allows changing the value by calling increment but this often is counter intuitive because I want to set the value of the progress. 

Could there be just another method on ProgressTask like `SetValue(double value)` or UpdateValue.

Current alternative is to use it like this `task.Increment(progress - task.Value);` but that is clunky and not intuitive.

### PR DESCRIPTION
**Pull request by OskarKlintrot**
I tried to keep it consistent with `MaxValue`.

Closes #272

### CODE REVIEW

**Comment by OskarKlintrot** [comment]
Sorry about the force-push mess. I had to make sure that I committed as myself to be able to sign the CLA.

**Comment by patriksvensson** [comment]
No worries! Force pushing is always OK on feature branches and PRs. I do it all the time to rewrite history in my PRs.

**Review by patriksvensson — APPROVED** [review]
LGTM! 👍🏻

**Comment by patriksvensson** [comment]
@OskarKlintrot Thanks for this PR! Much appreciated! 👍🏻

**Comment by OskarKlintrot** [comment]
No worries, glad I could help!

**Pull request merged**
