### PR TITLE
Add emoji code support

### PR DESCRIPTION
**Pull request by khellang**
Was just playing around. It's yours if you want it 😄

I have no clue where to plug it in, so I just did the replacement in `Segment` and added some emoji to the `Info` example 😅

I'll try to write some tests for the emoji replacement soon.

This is currently what the info sample looks like in my Rider terminal:

image

### CODE REVIEW

**Comment by patriksvensson** [comment]
@khellang Ooooh, awesome! I very much want this 😄 

I'm not sure where the correct place is to add it as well, but I would say `Segment` is OK by me.
Or perhaps it should be part of `Markup` parsing? Anyway, for now, putting it in `Segment` will do fine.

Thanks!

**Review by patriksvensson — APPROVED** [review]

**Comment by patriksvensson** [comment]
Merged! Thank you for your contribution. Much appreciated! 👍

**Comment by khellang** [comment]
Awesome. Perfect opportunity to test the new wcwidth implementation 😉

**Comment by patriksvensson** [comment]
@khellang Exactly! 😄

**Pull request merged**
