### PR TITLE
Early attempt at markdown rendering

### PR DESCRIPTION
**Pull request by mcon**
Fairly early days with this PR, but most commonly used markdown supported, notable items not supported: 
 - Abbreviations
 - Definition lists
 - Auto links
 - Footers

Example output:
image
image

## Questions / TODOs:
 - [ ] Would be nice to split test markdown into separate testcases
 - [ ] Are you happy with the rendering of the different document elements, spacing etc?
 - [ ] Given there's a dependency added on `Markdig`, I'm assuming you'd prefer a separate package as I've done?
 - [ ] Public doc comments
 - [ ] Check that the `CustomRenderable` added in `Rule` is fully consistent, add a test for it
 - [ ] Ensure unit tests use a mocked `HttpClient`

### CODE REVIEW

**Comment by patriksvensson** [comment]
@mcon Awesome! I know the PR isn't ready yet, but could we rename the module from `Spectre.Console.Markdig` to `Spectre.Console.Markdown`?

**Comment by khalidabuhakmeh** [comment]
Any chance you can include screenshots in this PR.

**Comment by patriksvensson** [comment]
@mcon Closing this due to inactivity. Feel free to reopen it if you want to continue working on it!

**Comment by SuperJMN** [comment]
Is this being worked? I'd like to render basic markdown to the console :)

**Comment by mcon** [comment]
> Is this being worked? I'd like to render basic markdown to the console :)

Hi @SuperJMN I'm not working on this one - feel free to continue where I left off!

**Comment by enginexon** [comment]
@patriksvensson 
Is this still interesting topic for community? Was it already implemented?

**Pull request closed without merging**
