### PR TITLE
Update exceptions.md

### PR DESCRIPTION
**Pull request by pitermarx**
Fix grammar

### CODE REVIEW

**Review by patriksvensson — APPROVED** [review]

**Comment by patriksvensson** [comment]
@pitermarx Thanks for this! Appreciated! 😊

**Comment by pitermarx** [comment]
No problem. Thank you for building this!
Have you thought of integrating this with Ben.Demystifier?
https://github.com/benaadams/Ben.Demystifier

**Comment by patriksvensson** [comment]
@pitermarx Yes, but I prefer not having any dependencies in the core library. You can render a demystified exception by demystifying it before rendering it.

```csharp
AnsiConsole.Exception(ex.Demystify());
```

**Comment by pitermarx** [comment]
yup. I'm just suggesting it to everyone until it is on .net by default
🤣

**Pull request merged**
