### PR TITLE
Add Progress.HideCompleted

### LINKED ISSUE #281: Progress to remove tasks as they are completed
I have a very long (up to 60+) list of tasks which I'd like to show progress for. They are not all added at the beginning, and some complete before new ones are added. I'd say the number of the started but non-completed tasks should not be larger then 20 at any time. Therefore I'd like an option to remove completed tasks from the display to keep the list visible. Consider that in addition to the progress bars there are going to be status messages displayed, just like in the Progress example.

A simple change in `DefaultProgressRenderer.cs` would give me what I need:
foreach (var task in context.GetTasks().**Where(tsk => !tsk.IsFinished)**)

Of course, the filtering should be controlled by an option (how about "HideCompleted(bool)", or "ClearCompleted(bool)"?) with the same syntax as "AutoClear". If you think this is a good idea, I can try and work on a Pull Request. The one thing I am not comfortable with is providing proper unit tests for the new feature for which I would need some guidance or hints. I noticed there seems to be only one test around AutoClear(true) (`Should_Render_Task_Correctly`). Something like that should be within my capabilities :-)

### PR DESCRIPTION
**Pull request by lstefano71**
Closes #281

### CODE REVIEW

**Comment by phil-scott-78** [comment]
This looks like a first-class PR to me. The build error looks like some sort of nuget restore issue.  I suspect if we rerun the build that it'll resolve itself. @patriksvensson, any concerns with manual starts like that? I haven't dug into the CI too much 

The one thing that would be nice to see would be the unit test verify the display with one task complete and one incomplete, but I'm not 100% sure if that's possible until the `StopTask()` #279 is resolved.

**Comment by patriksvensson** [comment]
> @patriksvensson, any concerns with manual starts like that? I haven't dug into the CI too much

No concerns. I've restarted the CI for you 😊

**Comment by lstefano71** [comment]
Thank you for your encouraging words. 
A look at the details of the build log for the MacOS version showed me that it must have been a fluke of the CI platform so I wasn't too worried about that.

> The one thing that would be nice to see would be the unit test verify the display with one task complete and one incomplete, but I'm not 100% sure if that's possible until the `StopTask()` #279 is resolved.

Indeed! I came to the same conclusion immediately after submitting the PR but I was already heading to bed for the day and while I am used to do coding in my pajamas in the wee hours of the morning, these days I need rest more than ever. I am about to submit a commit which tries to prove that a completed task will be hidden while tasks in progress still show up in the Console.

**Comment by lstefano71** [comment]
> I am about to submit a commit which tries to prove that a completed task will be hidden while tasks in progress still show up in the Console.

Improved unit test: bc4846028559

**Comment by lstefano71** [comment]
I found the source for the documentation and I thought I'd mention the new property in the "Configure" section of the page dedicated to the Progress widget in commit 7b207d9 to make it more discoverable by users like me who like to browse the docs.

**Review by phil-scott-78 — APPROVED** [review]

**Pull request merged**
